import Head from "next/head";
import Nav from "../components/Nav";
import Banner from "../components/Banner";

export default function Home() {
  return (
    <div className="px-2 tracking-wide  md:text-3xl">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />
    </div>
  );
}
