import Head from "next/head";
import Banner from "../components/home/Banner";
import About from "../components/about/About";

export default function Home() {
  return (
    <div className="px-2">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />
      <About />
    </div>
  );
}
